package com.business.impl;

import java.util.ArrayList;
import java.util.List;

import com.business.IClientBO;
import com.domain.Client;
import com.dtos.ClientDTO;
import com.persistence.IClientDAO;
import com.persistence.impl.ClientDAO;

public class ClientBO implements IClientBO {

  // DAO Injection
  private final IClientDAO clientDAO = new ClientDAO();

  /**
   * Adds a client into the database
   * 
   * @param clientDTO Client info
   */
  @Override
  public void addClient(ClientDTO clientDTO) {
    // Convert DTO -> Entity
    // NOTE: We cant pass ID because its autogenerated
    Client client = new Client(
        clientDTO.getName(),
        clientDTO.getTelephone(),
        clientDTO.getAddress(),
        clientDTO.getEmail());
    clientDAO.create(client);
  }

  /**
   * Deletes a client from the database
   * 
   * @param id ID of the client to delete
   */
  @Override
  public void deleteClient(Integer id) {
    clientDAO.delete(id);
  }

  /**
   * Gets a list of all the clients in the database
   */
  @Override
  public List<ClientDTO> getAllClients() {
    List<Client> clients = clientDAO.findAll();
    return mapListToDTO(clients);
  }

  /**
   * Gets a client by ID from the database
   * 
   * @param id ID of the client
   */
  @Override
  public ClientDTO getClientById(Integer id) {
    Client client = clientDAO.find(id);
    return (client != null) ? mapToDTO(client) : null;
  }

  /**
   * Gets a list with all the clients sorted by a name in the database
   * 
   * @param name Name of the client
   */
  @Override
  public List<ClientDTO> searchClientsByName(String name) {
    List<Client> clients = clientDAO.findByName(name);
    return mapListToDTO(clients);
  }

  /**
   * Updates a client from the database
   * 
   * @param clientDTO Info of the client that will be updated
   */
  @Override
  public void updateClient(ClientDTO clientDTO) {
    // 1. We search the original entity
    Client client = clientDAO.find(clientDTO.getIdClient());

    if (client != null) {
      // 2. Update the data
      client.setName(clientDTO.getName());
      client.setTelephone(clientDTO.getTelephone());
      client.setAddress(clientDTO.getAddress());
      client.setEmail(clientDTO.getEmail());

      // 3. Save changes
      clientDAO.update(client);
    }
  }

  /**
   * Converts a entity into a DTO object
   * 
   * @param entity Object entity
   */
  private ClientDTO mapToDTO(Client entity) {
    return new ClientDTO(
        entity.getIdClient(),
        entity.getName(),
        entity.getTelephone(),
        entity.getAddress(),
        entity.getEmail());
  }

  /**
   * Converts a list of entities into a list of DTO objects
   * 
   * @param entities List of entities
   */
  private List<ClientDTO> mapListToDTO(List<Client> entities) {
    List<ClientDTO> dtos = new ArrayList<>();
    for (Client c : entities) {
      dtos.add(mapToDTO(c));
    }
    return dtos;
  }
}
